{application, xmlists,
 [{description, "XMLists"},
  {vsn, "0.1.1"},
  {modules, [xmlists,
             htmlists]},
  {registered, []},
  {included_applications, []},
  {applications, [kernel, stdlib]},
  {env, []},
  {mod, []}]}.
